import tkinter as tk
from tkinter import filedialog
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem

def create_detailed_pdf(file_path, input_data=[]):
    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()
    bullet_style = styles["BodyText"]
    
    # Title and content
    title = Paragraph("Tasks List", styles["Title"])
    content = Paragraph("This PDF was generated by Gojo Satrou's power.", styles["BodyText"])
    spacer = Spacer(1, 20)
    
    # Define bullet points
    bullet_paragraph = ListFlowable(
    [
        ListItem(Paragraph("Item 1", bullet_style), bulletColor='#15171c'),
        ListItem(Paragraph("Item 2", bullet_style), bulletColor='#3576cc'),
        ListItem(Paragraph("Item 3", bullet_style), bulletColor='#15171c'),
        ListItem(Paragraph("Item 4", bullet_style), bulletColor='#3576cc'),

    ],
    bulletType='bullet',
    bulletFontSize=12,
)
    
    # Build the PDF
    doc.build([title, spacer, content, spacer, bullet_paragraph, spacer])

# Create the main window (it will not be displayed)
root = tk.Tk()
root.withdraw()  # Hide the main window

# Open the file dialog to choose the save location and filename
file_path = filedialog.asksaveasfilename(
    defaultextension=".pdf",
    filetypes=[("PDF files", "*.pdf")],
    title="Choose location to save the PDF"
)

# Check if the user provided a file path
if file_path:
    create_detailed_pdf(file_path)
    #print(f"PDF saved at: {file_path}")
#else:
    #print("Save operation was cancelled.")
