import json
import sys
import tkinter as tk
from tkinter import filedialog
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem

def create_detailed_pdf(file_path, active_tasks, completed_tasks):
    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()
    bullet_style = styles["BodyText"]

    # Title and content
    title = Paragraph("Tasks List", styles["Title"])
    content = Paragraph("This PDF was generated by Gojo Satrou's power.", styles["BodyText"])
    spacer = Spacer(1, 20)

    # Define bullet points
    bullet_paragraph = ListFlowable(
    [
        ListItem(Paragraph(f"Active Tasks: {task}", bullet_style)) for i, task in active_tasks
    ],
    bulletType='bullet',
    bulletFontSize=12,
    )

    # Build the PDF
    doc.build([title, spacer, content, spacer, bullet_paragraph, spacer])

# Create the main window (it will not be displayed)
root = tk.Tk()
root.withdraw()  # Hide the main window

# Open the file dialog to choose the save location and filename
file_path = filedialog.asksaveasfilename(
    defaultextension=".pdf",
    filetypes=[("PDF files", "*.pdf")],
    title="Choose location to save the PDF"
)

# Check if the user provided a file path
if file_path:
    active_tasks = json.loads(sys.argv[1])
    completed_tasks = json.loads(sys.argv[2])

    create_detailed_pdf(file_path, active_tasks, completed_tasks)
    #print(f"PDF saved at: {file_path}")
#else:
    #print("Save operation was cancelled.")
